$(document).ready(function(){
    $('.reviews__carusel').owlCarousel({
        loop:true,
        margin:10,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            768:{
                items:2
            },
            1024:{
                items:3
            },
            1200:{
                items:4
            },
        }
    });

});